name: Minimal Android CI Workflow

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up AWS Coretto 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64
      - name: Check Java
        run: java -version
      - name: Run Tests
        run: bash ./gradlew test --stacktrace
      - name: Check Gradle
        run: gradle -v
      - name: WTF jks 1
        run: ls -la
      - name: WTF jks 2
        run: ls -la ..
      - name: WTF jks 3
        run: ls -la ../..
  apk:
    name: Generate APK
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up AWS Coretto 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64
      - name: Build APK
        run: bash ./gradlew assembleRelease